//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace MyUmbracoWebApp.Models
{
	/// <summary>Contact</summary>
	[PublishedContentModel("contact")]
	public partial class Contact : PublishedContentModel, IBasicContentControls, IBasicTitleControls, IHideControls, IMainTitleImageControls, IUmbracoUrlaliasControls
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "contact";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Contact(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Contact, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Main Content: Enter the main content for this page in here
		///</summary>
		[ImplementPropertyType("mainContent")]
		public IHtmlString MainContent
		{
			get { return MyUmbracoWebApp.Models.BasicContentControls.GetMainContent(this); }
		}

		///<summary>
		/// Page Title: If left blan the name of the page will be used
		///</summary>
		[ImplementPropertyType("pageTitle")]
		public string PageTitle
		{
			get { return MyUmbracoWebApp.Models.BasicTitleControls.GetPageTitle(this); }
		}

		///<summary>
		/// Subtitle: Enter sub title
		///</summary>
		[ImplementPropertyType("subtitle")]
		public string Subtitle
		{
			get { return MyUmbracoWebApp.Models.BasicTitleControls.GetSubtitle(this); }
		}

		///<summary>
		/// Umbraco Navi Hide: Tick this box if you want to hide this page
		///</summary>
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return MyUmbracoWebApp.Models.HideControls.GetUmbracoNaviHide(this); }
		}

		///<summary>
		/// Main Image: Please choose an image to show under the title
		///</summary>
		[ImplementPropertyType("mainImage")]
		public IPublishedContent MainImage
		{
			get { return MyUmbracoWebApp.Models.MainTitleImageControls.GetMainImage(this); }
		}

		///<summary>
		/// Umbraco URL Alias: Enter an alternate url in there. Please note that the value you use must be lowercase, not use a leading slash and not use a trailing ".aspx" or trailing slash. If your are adding multiple values, they must be separated with a comma
		///</summary>
		[ImplementPropertyType("umbracoURLAlias")]
		public string UmbracoUrlalias
		{
			get { return MyUmbracoWebApp.Models.UmbracoUrlaliasControls.GetUmbracoUrlalias(this); }
		}
	}
}
