//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace MyUmbracoWebApp.Models
{
	// Mixin content Type 1066 with alias "mainTitleImageControls"
	/// <summary>Main Title Image Controls</summary>
	public partial interface IMainTitleImageControls : IPublishedContent
	{
		/// <summary>Main Image</summary>
		IPublishedContent MainImage { get; }
	}

	/// <summary>Main Title Image Controls</summary>
	[PublishedContentModel("mainTitleImageControls")]
	public partial class MainTitleImageControls : PublishedContentModel, IMainTitleImageControls
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "mainTitleImageControls";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public MainTitleImageControls(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<MainTitleImageControls, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Main Image: Please choose an image to show under the title
		///</summary>
		[ImplementPropertyType("mainImage")]
		public IPublishedContent MainImage
		{
			get { return GetMainImage(this); }
		}

		/// <summary>Static getter for Main Image</summary>
		public static IPublishedContent GetMainImage(IMainTitleImageControls that) { return that.GetPropertyValue<IPublishedContent>("mainImage"); }
	}
}
