//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace MyUmbracoWebApp.Models
{
	// Mixin content Type 1062 with alias "umbracoURLAliasControls"
	/// <summary>Umbraco URL Alias Controls</summary>
	public partial interface IUmbracoUrlaliasControls : IPublishedContent
	{
		/// <summary>Umbraco URL Alias</summary>
		string UmbracoUrlalias { get; }
	}

	/// <summary>Umbraco URL Alias Controls</summary>
	[PublishedContentModel("umbracoURLAliasControls")]
	public partial class UmbracoUrlaliasControls : PublishedContentModel, IUmbracoUrlaliasControls
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "umbracoURLAliasControls";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public UmbracoUrlaliasControls(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<UmbracoUrlaliasControls, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Umbraco URL Alias: Enter an alternate url in there. Please note that the value you use must be lowercase, not use a leading slash and not use a trailing ".aspx" or trailing slash. If your are adding multiple values, they must be separated with a comma
		///</summary>
		[ImplementPropertyType("umbracoURLAlias")]
		public string UmbracoUrlalias
		{
			get { return GetUmbracoUrlalias(this); }
		}

		/// <summary>Static getter for Umbraco URL Alias</summary>
		public static string GetUmbracoUrlalias(IUmbracoUrlaliasControls that) { return that.GetPropertyValue<string>("umbracoURLAlias"); }
	}
}
